### ISSUE TITLE
The data or model about Concatenate text segments

### ISSUE THREAD

**Issue by huihuiustc** [Spico197/CatalogExtraction#3]
Thanks for sharing great work!
Could you share the data or model about Concatenate text segments? Or tell me how to deal with the data of "Concatenate text segments"

**Comment by Spico197** [comment]
Sorry about the late response. Thanks for your attention in CED~

Thanks for your mention. I'll publish the data and scripts within this week. Please leave this issue open until the code is open-sourced.

**Comment by Spico197** [comment]
Hi there. Sorry for the long waiting. The text concatenation dataset pre-processing is acturally a little complex.
When talking about text concatenation, there are two methods for different usage:
1. Spliting the raw wiki data into chunks for each node: Since the processed datasets have been provided, you may want to know how did we split sentences and titles into chunks. Here's the script: https://github.com/Spico197/CatalogExtraction/blob/main/doctree/utils/make_further_split.py . Please install `jieba` before running, and beaware that the provided datasets have already been chunked.
2. For training the pipeline baseline system: I had uploaded the data and script before at: https://github.com/Spico197/CatalogExtraction/releases/tag/data-v1-patch
